[global]
index-url =  http://nxrm-ha-nexus-repo-service.nexus.svc.cluster.local/repository/pypi-internal/simple
trusted-host = nxrm-ha-nexus-repo-service.nexus.svc.cluster.local
#index-url =  http://<넥서스레포>/repository/pypi-internal/simple
#trusted-host = <넥서스레포>